version: "3.7"
services:
  c19-backend:
    image: quay.io/opusvl/c19:dev
    environment:
      DJANGO_POSTGRES_USER: ${DJANGO_POSTGRES_USER}
      DJANGO_POSTGRES_PASSWORD: ${DJANGO_POSTGRES_PASSWORD}
      DJANGO_POSTGRES_DB: ${DJANGO_POSTGRES_DB}
      C19_BACKEND_SECRET_KEY: ${C19_BACKEND_SECRET_KEY}
      C19_API_EHRBASE_URL: http://ehrbase:8080
      OIDC_RP_CLIENT_ID: ${OIDC_RP_CLIENT_ID}
      OIDC_RP_CLIENT_SECRET: ${OIDC_RP_CLIENT_SECRET}
      OIDC_RP_SIGN_ALGO: ${OIDC_RP_SIGN_ALGO}
      OIDC_OP_JWKS_ENDPOINT: ${OIDC_OP_JWKS_ENDPOINT}
      OIDC_OP_AUTHORIZATION_ENDPOINT: ${OIDC_OP_AUTHORIZATION_ENDPOINT}
      OIDC_OP_TOKEN_ENDPOINT: ${OIDC_OP_TOKEN_ENDPOINT}
      OIDC_OP_USER_ENDPOINT: ${OIDC_OP_USER_ENDPOINT}
      OIDC_CLIENT_ASSERTION: ${OIDC_CLIENT_ASSERTION}
      OIDC_CLIENT_ASSERTION_SIGN_ALGO: ${OIDC_CLIENT_ASSERTION_SIGN_ALGO}
      OIDC_CLIENT_ASSERTION_SIGN_KEY: ${OIDC_CLIENT_ASSERTION_SIGN_KEY}
      OIDC_RP_SCOPES: ${OIDC_RP_SCOPES}
      C19_BACKEND_EHRBASE_URL: http://ehrbase:8080
      C19_BACKEND_CORS_ORIGIN_WHITELIST: ${C19_BACKEND_CORS_ORIGIN_WHITELIST}
    volumes:
      - ./c19-backend:/app
    #  - ../mozilla-me/mozilla_django_oidc:/usr/local/lib/python3.8/site-packages/mozilla_django_oidc
    ports:
      - ${C19_BACKEND_PORT}:8000
    depends_on:
     - django_postgres
    networks:
      - django_net
      - ehrbase_net

  django_postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: ${DJANGO_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DJANGO_POSTGRES_PASSWORD}
    networks:
      - django_net

  ehrdb:
    image: ehrbaseorg/ehrbase-postgres:latest
    volumes:
      - "./postgres/:/var/lib/postgresql/data/:rw"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${EHRBASE_DB}", "-U", "${EHRBASE_USER}"]
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      EHRBASE_USER: ${EHRBASE_USER}
      EHRBASE_PASSWORD: ${EHRBASE_PASSWORD}
    networks:
      - ehrbase_net
    restart: always

  ehrbase:
    image: ehrbaseorg/ehrbase:next
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      SYSTEM_NAME: ${SYSTEM_NAME}
    ports:
      - "${EHRBASE_PORT}:8080"
    networks:
      - ehrbase_net
    restart: always

  testprovider:
    stdin_open: true
    tty: true
    image: mozilla/oidc-testprovider:oidc_testprovider-latest
    ports:
      - "${TESTPROVIDER_PORT}:8080"
    networks:
      - django_net
  

networks:
  django_net:
  ehrbase_net:
