"""
Django settings for C19 project.

Generated by 'django-admin startproject' using Django 3.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['C19_BACKEND_SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mozilla_django_oidc',
    'corsheaders',
    'rest_framework',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'C19.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'C19.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ['DJANGO_POSTGRES_DB'],
        'USER': os.environ['DJANGO_POSTGRES_USER'],
        'PASSWORD': os.environ['DJANGO_POSTGRES_PASSWORD'],
        'HOST': 'django_postgres',
        'PORT': 5432,
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # until we have OAuth
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
    ],
}

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

EHRBASE_CONNECTION_PARAMS = dict(
    base_url=os.environ['C19_BACKEND_EHRBASE_URL'],
)

# mozilla-django-oidc

AUTHENTICATION_BACKENDS = (
    'mozilla_django_oidc.auth.OIDCAuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',
)

OIDC_RP_CLIENT_ID = os.environ['OIDC_RP_CLIENT_ID']
OIDC_RP_CLIENT_SECRET = os.environ['OIDC_RP_CLIENT_SECRET']
OIDC_RP_SIGN_ALGO = os.environ['OIDC_RP_SIGN_ALGO']
OIDC_OP_JWKS_ENDPOINT = os.environ['OIDC_OP_JWKS_ENDPOINT']
OIDC_OP_AUTHORIZATION_ENDPOINT = os.environ['OIDC_OP_AUTHORIZATION_ENDPOINT']
OIDC_OP_TOKEN_ENDPOINT = os.environ['OIDC_OP_TOKEN_ENDPOINT']
OIDC_OP_USER_ENDPOINT = os.environ['OIDC_OP_USER_ENDPOINT']

OIDC_CLIENT_ASSERTION = os.environ['OIDC_OP_USER_ENDPOINT']
OIDC_CLIENT_ASSERTION_SIGN_ALGO = os.environ['OIDC_CLIENT_ASSERTION_SIGN_ALGO']
OIDC_CLIENT_ASSERTION_SIGN_KEY = b'-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDvw99j9kTqx8VX\nAt5ajnMMJhZ6GLGTQwZbqSfa7SFYOjz8y/lT0UYL9X6oPOccQDl26tnblcdXnlYX\nKN5C2SSFfeLk4H+VJxMWJnRMhTYBXMyIqtfzhCYtNyDaYzIHt5vJTE+3/KAOQ75J\nR0JDrEC811VTUd8YZYazXL5i8f8gzjOjW167aavCLjT+DAl2G7Fs0RKFyjfjS4Yj\nSv8dFgenMtvwpv9hylgbHCvIGy69GDNBZbFgi+O4wrXhZVx24seMQBF9EpLt50km\nrOMRF4y9jsbt73XwG3UeqZF0fcAm+MPzE5iT98PNiXLObDWLraVmqDdzQffqQEh8\ngwPXRMmxAgMBAAECggEAaAVx2LuSgM21Bx/+eglNTpsDq2slN3+ftYq4+NliWxXB\nOegAvuWPX0bd8X2iwvX2OGqBpCviNVhDf37ClvwARU4tbyEbGQm/1R9P25b7rDGn\npy9/y22s5ncBcN4SaZi2JOpPt8IJasbnOoGI9TU5TPSbVy+w+7Oocg6tpt3Y01Dr\nr+awVTW7jhtdf/nNIIqtFyfGunO7wjdmMqeUAFFW4hbX4Y/Ngjoijf4VU3Prfou7\nThgx7I2c5KX1UnQWwjBuUMtSdSxPr0X709HWNxoPvOpMw7aR1nQ4SE+K4r5VTqGW\nTGtDksToSdyeMR3/D2QCK3IAsGsWffbjKi890fakQQKBgQD/pnu+Yoyk68SY4JgZ\nguflZQI2a/nFZ9tCN/Nl8+KkD7knhiAwOt5n5CZgg8zINKhC/rDUiSu7K5t3TlTl\nTk7SpOPPDcZ6K1xorrdmGc0q3+GFVZiriGqBbmPvwvHZBvMYlbMP86eGcZsvNnmG\nvdvqDvb8OnlrMkY2esx9ejRgGQKBgQDwF9O2Y48hJce6bVt5OaOyhAg/+djkBLA2\n3RLOAQ882GKOhCdcdGIMwUk6S29WFELwk8eUvhj9YGy1KFBMmtmofOw+QKtpDImI\nzVWVYBcZXnSLmIHQYhvDpkL0rWchr1oNTlzsXjj2/SaCWeb+mX+kBzB6c1FlhDPd\nCajW3PKJWQKBgQDgJaM3gQaZjxI3jCwvqgQSsCZpevBq8a1feNkSmewsNpD7o3DT\neLoJ0xMG6miBXRHuc4qtPnu2RvyvdWGgD7GypNoMb6KG+T+zlQS+I38syVDda/hI\n5XmkdBpxXLZZt+sqsg5mvRY0HaWXlqakyhBoPqi067wLje/b0n06wwvq+QKBgGmU\n0NFgLs0Q5Cgjdxp0MnyKe2ZG5Q5A0Y0O4voclSrYrV6m1vhdZdDeHum3ypo8BsPs\n+NN8VVj3UlbIB6foYNcrOGiX38kubjzurzglLYNGelH5Gv0cZ8E+GCupJbU2e49m\nao63UK2s3YZtKpvDvNHRJ4xxsdXGsVf+q3TxbObhAoGBAPPvzxA/a+1qk0rTVp2/\nSmXUWLLfBmsLveIYdfYfiMZ0Unz1FetZkoIQiDPc5faKJt7A666jq/l64uSqG3JE\n6RYz/ovckcAGS6j1tt77s1XuFa3JIT9ytGWJkviqtOwVZqv32EW55rC/9WGz5T+B\n40oGLuWNcopp6JWGCY+LgsGa\n-----END PRIVATE KEY-----\n'

OIDC_RP_SCOPES = os.environ['OIDC_RP_SCOPES']

LOGOUT_REDIRECT_URL = '/'
LOGIN_REDIRECT_URL = '/'

CORS_ORIGIN_WHITELIST = tuple(
    os.environ['C19_BACKEND_CORS_ORIGIN_WHITELIST'].split('|'))


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        # 'django': {
        #     'handlers': ['console'],
        #     'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
        #     'propagate': False,
        # },
        'mozilla_django_oidc': {
            'handlers': ['console'],
            'level': 'DEBUG'
        },
    },
}